-- Enable UUID extension just in case
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the applications table
CREATE TABLE IF NOT EXISTS public.applications (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name        TEXT NOT NULL,
  email            TEXT NOT NULL,
  phone            TEXT NOT NULL,
  dob              DATE,
  gender           TEXT,
  city             TEXT,
  profession       TEXT,
  education        TEXT,
  preferences      JSONB,
  about            JSONB,
  payment_method   TEXT,
  submitted_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- Policy for Public Insert (Form Submissions)
DROP POLICY IF EXISTS "Allow public submissions" ON public.applications;
CREATE POLICY "Allow public submissions"
  ON public.applications
  FOR INSERT
  TO public
  WITH CHECK (true);

-- Policy for Admin Read (Dashboard)
DROP POLICY IF EXISTS "Allow admin read" ON public.applications;
CREATE POLICY "Allow admin read"
  ON public.applications
  FOR SELECT
  TO public
  USING (true);
